services:

  mqtt-kafka-connector:
    build:
      dockerfile: ./Dockerfile
      context: .
    environment:
      - 'PS1=$$(whoami)@$$(hostname):$$(pwd) $$ '
    env_file:
      - .env.docker
    volumes:
      - .:/app
    networks:
      - piklema-network

networks:
  piklema-network:
    external: true
