services:
    kafka:
        image: bitnami/kafka:3.4
        container_name: kafka
        ports:
            - "9092:9092"
        environment:
            # Режим без ZooKeeper (KRaft)
            - KAFKA_CFG_PROCESS_ROLES=broker,controller
            - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
            - KAFKA_CFG_NODE_ID=0

            # Настройка слушателей (listeners)
            # INTERNAL://:19092 - для внутреннего трафика между контейнерами (сервис mkc)
            # EXTERNAL://:9092 - для внешнего трафика с хоста
            # CONTROLLER://:9093 - для KRaft
            - KAFKA_CFG_LISTENERS=INTERNAL://:19092,EXTERNAL://:9092,CONTROLLER://:9093
            - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:19092,EXTERNAL://localhost:9092

            # Сопоставление протоколов безопасности
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT

            # Для внутренней коммуникации брокеров
            - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL

            # Настройки для контроллера (в режиме KRaft)
            - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

            # Дополнительные настройки для разработки
            - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
            - KAFKA_CFG_NUM_PARTITIONS=1
            - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=1

    mqtt:
        image: eclipse-mosquitto:2
        ports:
            - "1883:1883"
        volumes:
            - ./docker/mqtt_broker/mosquitto:/mosquitto

    prometheus:
        image: prom/prometheus:latest
        profiles: ["monitoring"]
        volumes:
            - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        command: --config.file=/etc/prometheus/prometheus.yml
        ports:
            - "9090:9090"

    grafana:
        image: grafana/grafana:latest
        profiles: ["monitoring"]
        ports:
            - "3000:3000"
        environment:
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=admin
        depends_on:
            - prometheus

    mkc:
        build: .
        environment:
            - KAFKA_BOOTSTRAP_SERVERS=kafka:19092
            - MQTT_HOST=mqtt
            - MQTT_PORT=1883
            - PROMETHEUS_PORT=8000
        ports:
            - "8000:8000"
        depends_on:
            - kafka
            - mqtt
