[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = ["-p", "no:warnings"]
plugins = ["pytest_asyncio", "pytest_mock"]
asyncio_mode = 'auto'

[tool.coverage.report]
show_missing = true
skip_empty = true
fail_under = 86

[tool.black]
line-length = 79
skip-string-normalization = true
target-version = ['py310']

[tool.isort]
profile = "black"
line_length = 79
