# This is a basic workflow that is manually triggered

name: build and push image

on:
  workflow_call:
    outputs:
      release_tag:
        description: "Release tag"
        value: ${{ jobs.build-and-push-image.outputs.release_tag }}
  push:
    tags:
      - '*'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{ steps.release_tag.outputs.release_tag }}

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get release version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - id: release_tag
      run: echo "::set-output name=release_tag::${{ env.RELEASE_VERSION }}"

    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v3
      with:
        image: piklema/mqtt-kafka-connector
        tag: ${{ env.RELEASE_VERSION }}
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
